### ISSUE TITLE
Opening PSLinkCell with PSListController crashes settings

### ISSUE THREAD

**Issue by tomaszpoliszuk** [ArtikusHG/PreferenceLoader#6]
Two users so far reported me that this issue exist, relevant parts of code are [App Switcher Cards](https://github.com/tomaszpoliszuk/AppSwitcherController/blob/364402378c2cbaa10031b49674e56a04bbc85ab4/AppSwitcherControllerPreferences/Resources/Root.plist#L40-L63) and [App Switcher Background](https://github.com/tomaszpoliszuk/AppSwitcherController/blob/master/AppSwitcherControllerPreferences/Resources/Root.plist#L64-L141).

Have a nice day!

**Comment by ArtikusHG** [comment]
issue is now fixed, idk since which version but it works so yeah lol
